# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop
- qa
- main

resources:
  repositories:
    - repository: templates
      type: git
      name: DevOps/pipeline-library

variables:
  projectName: Microservices
  appName: appcontoso
  buildTool: maven
  containerRegistrySC: microservices-dev

stages:
- template: CI/CI-Pipeline-Template.yml@templates
  parameters:
    projectName: ${{ variables.projectName }}
    appName: ${{ variables.appName }}
    buildTool: ${{ variables.buildTool }}
    containerRegistrySC: ${{ variables.containerRegistrySC }}